export type League = 'MLS' | 'Allsvenskan' | 'Liga MX' | 'Brazil Serie A';
export type MatchState = 'QUALIFIED' | 'WATCHING' | 'TRIGGER' | 'CANCELLED';

export interface TradingMatch {
  id: string;
  league: League;
  home: string;
  away: string;
  minute: number | null;
  status: 'PRE' | 'LIVE' | 'HT' | 'FT';
  kickoff?: string | null;
  scoreHome: number;
  scoreAway: number;
  cornersHome: number;
  cornersAway: number;
  prematchCornerLine: number;
  prematchGoalLine: number;
  favourite: 'HOME' | 'AWAY';
  handicap: number;
  favouriteCoveringHandicap: boolean;
  favouriteLosing: boolean;
  ftGoalOverClear: boolean;
  liveCornerLine?: number | null;
  liveGoalLine?: number | null;
  checkedAt?: string | null;
  state?: MatchState;
  reasons?: string[];
  winProbability?: number;
  notable?: boolean;
  notableScore?: number;
  sourceSummary?: string;
  sourceUrls?: string[];
  htAction?: 'H2_GOALS_AND_CORNERS' | 'H2_CORNERS' | 'NO_ENTRY' | 'NEED_INPUT';
  htAdvice?: string;
  htConfidence?: 'HIGH' | 'MEDIUM' | 'LOW';
  htMissingInputs?: string[];
  htSourceSummary?: string;
  htSourceUrls?: string[];
  htCheckedAt?: string | null;
  htEvaluationType?: 'V1_TRIGGER' | 'V1_CANCEL_DATA' | 'NEED_INPUT';
  h2GoalsAssessment?: 'V1_SUPPORTED' | 'V1_NOT_SUPPORTED' | 'UNRESOLVED';
  h2CornersAssessment?: 'V1_SUPPORTED' | 'V1_NOT_SUPPORTED' | 'UNRESOLVED';
  htDataNote?: string;
  htScoreHome?: number | null;
  htScoreAway?: number | null;
  htCornersHome?: number | null;
  htCornersAway?: number | null;
  redCardsHome?: number | null;
  redCardsAway?: number | null;
  ftScoreHome?: number | null;
  ftScoreAway?: number | null;
  ftCornersHome?: number | null;
  ftCornersAway?: number | null;
  ftCheckedAt?: string | null;
  ftSourceSummary?: string;
  ftSourceUrls?: string[];
  h2ActualGoals?: number | null;
  h2ActualCorners?: number | null;
  researchPhase?: 'HT' | 'FT' | 'MANUAL';
}
